title: Thomas Barlow # your name (or website title) here
logo: "/images/headshot.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello, I'm a third year computer engineering student at the University of Cincinnati. My last semester was spent working on virtual and augmented reality developments at Siemens Software. 
  <br><br>
  <a href="https://www.linkedin.com/in/thomas-barlow/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="http://thomasjbarlow.com/work_experience">Work Experience</a> 
  <br>
  <a href="http://thomasjbarlow.com/skribblio_bot">Skribblio Drawing Bot</a> 
  <br>
  <a href="http://thomasjbarlow.com/youtube_channel">YouTube Channel</a> 
  <br>
  <a href="http://thomasjbarlow.com/model_design">Model Design and 3D Printing</a> 
  <br>
  <a href="http://thomasjbarlow.com/discord_search_bot">Discord Search Bot</a> 
  <br>
  <a href="http://thomasjbarlow.com/work_experience">ThePageFlip Book Borrowing Platform</a> 
  <br>
  


  
theme: jekyll-theme-minimal
google_analytics: UA-141278946-1 # your Google Analytics tracking ID here
